# Site settings
title: mikebell.io Blog & Stuff
email: hello@mikebell.io
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mikebell.io" # the base hostname & protocol for your site
twitter_username: mikebell_
github_username:  mikebell

gems:
  - jekyll-paginate

# Build settings
markdown: kramdown
highlighter: rouge

permalink: :title
paginate: 10
excerpt_separator: "\n\n"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
